/**
 * Self-contained PDF report engine — zero dependencies.
 * Ported 1:1 from the legacy calculators page (_D class + pdf* primitives)
 * so report output is visually identical to the old site.
 *
 * Units: millimetres. Page: US Letter (612x792pt).
 */
import type { BuiltPdf } from "./types";

const M = 72 / 25.4; // mm → pt
const PAGE_H = 792; // pt
const PAGE_W_MM = 216;
const MARGIN_MM = 14;
const CONTENT_W_MM = 188;
const PAGE_SAFE_MM = 250; // max y before page break

type RGB = [number, number, number];

function parseColor(v: number | [number, number, number]): RGB {
  if (typeof v === "number") return [v / 255, v / 255, v / 255];
  return [v[0] / 255, v[1] / 255, v[2] / 255];
}

/** Approximate Helvetica width (same heuristic as legacy _tw). */
function textWidth(s: string, fs: number): number {
  let w = 0;
  for (let i = 0; i < s.length; i++) {
    const c = s.charCodeAt(i);
    if (c >= 65 && c <= 90) w += 0.72;
    else if ((c >= 97 && c <= 122) || (c >= 48 && c <= 57)) w += 0.52;
    else if (c === 32) w += 0.28;
    else if (c === 36) w += 0.5;
    else if (c === 37) w += 0.75;
    else if (c === 44 || c === 45 || c === 46) w += 0.34;
    else if (c === 38) w += 0.8;
    else w += 0.5;
  }
  return w * fs;
}

/** Escape text for PDF literal strings (same as legacy _es). */
function esc(s: string): string {
  return String(s)
    .replace(/[\u2018\u2019]/g, "'")
    .replace(/[\u201C\u201D]/g, '"')
    .replace(/[\u2013\u2014]/g, "-")
    .replace(/[\u2122\u2120]/g, "(TM)")
    .replace(/[\u00AE]/g, "(R)")
    .replace(/[^\x20-\x7E]/g, "?")
    .replace(/\\/g, "\\\\")
    .replace(/\(/g, "\\(")
    .replace(/\)/g, "\\)");
}

interface Page {
  ops: string[];
}

/** jsPDF-compatible writer. Mirrors the legacy _D API. */
export class PdfDoc {
  private pages: Page[] = [{ ops: [] }];
  private fs = 10;
  private bold = false;
  private textColor: RGB = [0, 0, 0];
  private drawColor: RGB = [200 / 255, 200 / 255, 200 / 255];
  private fillColor: RGB = [240 / 255, 247 / 255, 251 / 255];
  reportName = "getsetsold.ca";
  reportDate = new Date().toLocaleDateString("en-CA");

  private ops(): string[] {
    return this.pages[this.pages.length - 1].ops;
  }

  setFont(_f: string, s: "normal" | "bold" | "bolditalic" = "normal"): void {
    this.bold = s === "bold" || s === "bolditalic";
  }
  setFontSize(s: number): void {
    this.fs = s;
  }
  setTextColor(r: number | [number, number, number], g?: number, b?: number): void {
    this.textColor = g === undefined ? parseColor(r as number) : [(r as number) / 255, g / 255, (b as number) / 255];
  }
  setDrawColor(r: number | [number, number, number], g?: number, b?: number): void {
    this.drawColor = g === undefined ? parseColor(r as number) : [(r as number) / 255, g / 255, (b as number) / 255];
  }
  setFillColor(r: number | [number, number, number], g?: number, b?: number): void {
    this.fillColor = g === undefined ? parseColor(r as number) : [(r as number) / 255, g / 255, (b as number) / 255];
  }

  text(t: string, x: number, y: number, opt?: { align?: "right" }): void {
    let rx = x * M;
    if (opt?.align === "right") rx -= textWidth(String(t), this.fs);
    const [r, g, b] = this.textColor;
    this.ops().push(
      `BT ${this.bold ? "/F2" : "/F1"} ${this.fs} Tf ${r} ${g} ${b} rg ${rx} ${PAGE_H - y * M} Td (${esc(t)}) Tj ET`,
    );
  }

  line(x1: number, y1: number, x2: number, y2: number): void {
    const [r, g, b] = this.drawColor;
    this.ops().push(
      `${r} ${g} ${b} RG ${x1 * M} ${PAGE_H - y1 * M} m ${x2 * M} ${PAGE_H - y2 * M} l S`,
    );
  }

  rect(x: number, y: number, w: number, h: number, s: "F" | "FD" | "DF"): void {
    if (s !== "F" && s !== "FD" && s !== "DF") return;
    const [r, g, b] = this.fillColor;
    this.ops().push(`${r} ${g} ${b} rg ${x * M} ${PAGE_H - (y + h) * M} ${w * M} ${h * M} re f`);
  }

  addPage(): void {
    this.pages.push({ ops: [] });
  }

  /** Serialize to PDF bytes, injecting branded header/footer + page numbers. */
  toBytes(): Uint8Array {
    const total = this.pages.length;
    const finalPages: string[][] = [];
    for (let pi = 0; pi < total; pi++) {
      const ops: string[] = [];
      const grey = `${0.47} ${0.47} ${0.47}`;
      // Header
      ops.push(`BT /F1 9 Tf ${grey} rg ${14 * M} ${PAGE_H - 14 * M} Td (${esc(`Generated by ${this.reportName} - ${this.reportDate}`)}) Tj ET`);
      const [dr, dg, db] = this.drawColor;
      ops.push(`${dr} ${dg} ${db} RG ${14 * M} ${PAGE_H - 17 * M} m ${202 * M} ${PAGE_H - 17 * M} l S`);
      // Content
      ops.push(...this.pages[pi].ops);
      // Footer
      ops.push(`${dr} ${dg} ${db} RG ${14 * M} ${PAGE_H - 264 * M} m ${202 * M} ${PAGE_H - 264 * M} l S`);
      ops.push(`BT /F1 7.5 Tf ${grey} rg ${14 * M} ${PAGE_H - 267 * M} Td (${esc("getsetsold.ca - Rohit Sharma, Real Estate Agent, Lombard Group Real Estate Inc.")}) Tj ET`);
      ops.push(`BT /F1 7.5 Tf ${grey} rg ${14 * M} ${PAGE_H - 271 * M} Td (${esc("Visit getsetsold.ca for more tools | Phone: +1-416-605-7488 | This report is for informational purposes only.")}) Tj ET`);
      const pgTxt = `Page ${pi + 1} of ${total}`;
      const pgWmm = ((textWidth(pgTxt, 8) * 25.4) / 72);
      ops.push(`BT /F1 8 Tf ${grey} rg ${(202 - pgWmm) * M} ${PAGE_H - 267 * M} Td (${esc(pgTxt)}) Tj ET`);
      finalPages.push(ops);
    }

    // Object numbering: 1..2 reserved-ish layout mirroring legacy _bp
    const d: string[] = [];
    const push = (s: string): number => {
      d.push(s);
      return d.length;
    };
    const f1 = push("<< /Type /Font /Subtype /Type1 /BaseFont /Helvetica >>");
    const f2 = push("<< /Type /Font /Subtype /Type1 /BaseFont /Helvetica-Bold >>");
    const pgs = push(""); // Pages (filled later)
    const cat = push(""); // Catalog (filled later)
    const pn: number[] = [];
    const cn: number[] = [];
    for (let i = 0; i < finalPages.length; i++) {
      const st = finalPages[i].join("\n");
      cn.push(push(`<< /Length ${st.length} >>\nstream\n${st}\nendstream`));
      pn.push(push("")); // Page dict (filled later)
    }
    for (let i = 0; i < finalPages.length; i++) {
      d[pn[i] - 1] =
        `<< /Type /Page /Parent ${pgs} 0 R /MediaBox [0 0 612 792] /Contents ${cn[i]} 0 R /Resources << /Font << /F1 ${f1} 0 R /F2 ${f2} 0 R >> >> >>`;
    }
    d[pgs - 1] = `<< /Type /Pages /Kids [${pn.map((v) => `${v} 0 R`).join(" ")}] /Count ${finalPages.length} >>`;
    d[cat - 1] = `<< /Type /Catalog /Pages ${pgs} 0 R >>`;

    let pdf = "%PDF-1.4\n";
    const offsets: number[] = [];
    for (let i = 0; i < d.length; i++) {
      offsets.push(pdf.length);
      pdf += `${i + 1} 0 obj\n${d[i]}\nendobj\n`;
    }
    const xr = pdf.length;
    pdf += `xref\n0 ${d.length + 1}\n0000000000 65535 f \n`;
    for (const o of offsets) pdf += `${String(o).padStart(10, "0")} 00000 n \n`;
    pdf += `trailer\n<< /Size ${d.length + 1} /Root ${cat} 0 R >>\nstartxref\n${xr}\n%%EOF`;

    const bytes = new Uint8Array(pdf.length);
    for (let i = 0; i < pdf.length; i++) bytes[i] = pdf.charCodeAt(i) & 0xff;
    return bytes;
  }
}

/* ── Spacing system (mirrors legacy _SP) ─────────────────────────── */
export const SP = { BLOCK_GAP: 7, LINE_GAP: 3.5, CONTAINER_PAD: 3, PAGE_SAFE: PAGE_SAFE_MM };

/** Report cursor: doc + current y (mm). */
export interface ReportCtx {
  doc: PdfDoc;
  y: number;
}

export function makeReport(name: string, reportDate?: string): ReportCtx {
  const doc = new PdfDoc();
  doc.reportName = "getsetsold.ca";
  if (reportDate) doc.reportDate = reportDate;
  void name;
  return { doc, y: 24 };
}

export function reportFilename(name: string): string {
  return `getsetsold-${name}-Report.pdf`;
}

function needPage(p: ReportCtx, needMm: number): void {
  if (p.y + needMm > SP.PAGE_SAFE) {
    p.doc.addPage();
    p.y = 20;
  }
}

export function pdfGap(p: ReportCtx, mm?: number): ReportCtx {
  const gap = mm ?? SP.BLOCK_GAP;
  if (p.y + gap > SP.PAGE_SAFE) {
    p.doc.addPage();
    p.y = 20;
    return p;
  }
  p.y += gap;
  return p;
}

export function pdfTitle(p: ReportCtx, title: string): ReportCtx {
  if (p.y > 258) {
    p.doc.addPage();
    p.y = 20;
  }
  p.doc.setFontSize(20);
  p.doc.setTextColor([1, 58, 81]);
  p.doc.setFont("helvetica", "bold");
  p.doc.text(title, MARGIN_MM, p.y);
  p.y += SP.LINE_GAP * 2;
  p.doc.setDrawColor([1, 58, 81]);
  p.doc.line(MARGIN_MM, p.y, 80, p.y);
  p.y += SP.BLOCK_GAP;
  return p;
}

export function pdfHeading(p: ReportCtx, text: string): ReportCtx {
  pdfGap(p, SP.BLOCK_GAP);
  p.doc.setFontSize(11);
  p.doc.setTextColor([1, 58, 81]);
  p.doc.setFont("helvetica", "bold");
  p.doc.text(text, MARGIN_MM, p.y);
  p.y += SP.LINE_GAP;
  return p;
}

export function pdfSubtext(p: ReportCtx, text: string, fs = 9, color: [number, number, number] = [100, 100, 100], bold = false): ReportCtx {
  p.doc.setFontSize(fs);
  p.doc.setTextColor(color);
  p.doc.setFont("helvetica", bold ? "bold" : "normal");
  p.doc.text(text, MARGIN_MM, p.y);
  p.y += SP.LINE_GAP;
  return p;
}

export function pdfHighlight(p: ReportCtx, label: string, big: string, sub?: string): ReportCtx {
  needPage(p, 20);
  const h = sub ? 18 : 14;
  p.doc.setFillColor([1, 58, 81]);
  p.doc.rect(MARGIN_MM, p.y - 2, 3, h, "F");
  p.doc.setFillColor([240, 247, 251]);
  p.doc.rect(17, p.y - 2, 185, h, "F");
  p.doc.setFontSize(9);
  p.doc.setTextColor(120);
  p.doc.setFont("helvetica", "normal");
  p.doc.text(label.toUpperCase(), 21, p.y + 3);
  p.doc.setFontSize(16);
  p.doc.setTextColor([1, 58, 81]);
  p.doc.setFont("helvetica", "bold");
  p.doc.text(big, 21, p.y + 9);
  if (sub) {
    p.doc.setFontSize(11);
    p.doc.setTextColor([2, 85, 119]);
    p.doc.text(sub, 21, p.y + 14);
  }
  p.y += h + SP.CONTAINER_PAD;
  return p;
}

export type PdfCell = string | { t: string; bold?: boolean; color?: [number, number, number] };

export function pdfTable(p: ReportCtx, cols: string[], rows: PdfCell[][]): ReportCtx {
  const colW = CONTENT_W_MM / cols.length;
  const startX = MARGIN_MM;
  const endX = startX + CONTENT_W_MM;
  needPage(p, 26);

  const drawHdr = () => {
    p.doc.setFillColor([1, 58, 81]);
    p.doc.rect(startX, p.y - 1, CONTENT_W_MM, 9, "F");
    p.doc.setFontSize(8.5);
    p.doc.setTextColor(255);
    p.doc.setFont("helvetica", "bold");
    for (let c = 0; c < cols.length; c++) {
      if (c === 0) p.doc.text(cols[c], startX + 4, p.y + 5);
      else p.doc.text(cols[c], startX + c * colW + colW - 4, p.y + 5, { align: "right" });
    }
    for (let c = 1; c < cols.length; c++) {
      p.doc.setDrawColor(255);
      p.doc.line(startX + c * colW, p.y - 1, startX + c * colW, p.y + 8);
    }
    p.y += 10;
  };
  drawHdr();

  for (let r = 0; r < rows.length; r++) {
    if (p.y + 8 > 258) {
      p.doc.addPage();
      p.y = 20;
      drawHdr();
    }
    const rh = 8;
    if (r % 2 === 0) {
      p.doc.setFillColor([249, 250, 251]);
      p.doc.rect(startX, p.y - 1, CONTENT_W_MM, rh, "F");
    }
    p.doc.setDrawColor(228);
    p.doc.line(startX, p.y + rh - 2, endX, p.y + rh - 2);
    for (let c = 1; c < cols.length; c++) {
      p.doc.setDrawColor(235);
      p.doc.line(startX + c * colW, p.y - 1, startX + c * colW, p.y + rh - 2);
    }
    const cells = rows[r];
    for (let c = 0; c < cols.length; c++) {
      const cv = cells[c];
      let txt = "";
      let isBold = false;
      let clr: [number, number, number] = [50, 50, 50];
      if (cv && typeof cv === "object") {
        txt = cv.t || "";
        isBold = !!cv.bold;
        clr = cv.color || [50, 50, 50];
      } else {
        txt = cv == null || cv === "" ? "N/A" : String(cv);
      }
      txt = !txt || txt.trim() === "" ? "N/A" : txt;
      p.doc.setTextColor(clr);
      p.doc.setFont("helvetica", isBold ? "bold" : "normal");
      if (c === 0) p.doc.text(txt, startX + 4, p.y + 4);
      else p.doc.text(txt, startX + c * colW + colW - 4, p.y + 4, { align: "right" });
    }
    p.y += rh;
  }
  p.y += SP.CONTAINER_PAD;
  return p;
}

export function pdfRow(
  p: ReportCtx,
  label: string,
  val: string,
  color: [number, number, number] = [50, 50, 50],
  bold = false,
): ReportCtx {
  p.doc.setFontSize(9);
  p.doc.setFont("helvetica", bold ? "bold" : "normal");
  p.doc.setTextColor(80);
  p.doc.text(label, 18, p.y);
  p.doc.setTextColor(color);
  p.doc.text(val, 202, p.y, { align: "right" });
  p.y += SP.LINE_GAP;
  return p;
}

export function pdfTips(p: ReportCtx, title: string, tips: string[]): ReportCtx {
  if (!tips || tips.length === 0) return p;
  pdfGap(p, SP.BLOCK_GAP);
  p.doc.setFontSize(11);
  p.doc.setTextColor([1, 58, 81]);
  p.doc.setFont("helvetica", "bold");
  p.doc.text(title, MARGIN_MM, p.y);
  p.y += SP.LINE_GAP;
  for (const tip of tips) {
    needPage(p, 10);
    const plain = tip.replace(/<[^>]*>/g, "");
    const lines = wrapText(plain, 9, 180);
    p.doc.setFontSize(9);
    p.doc.setTextColor([50, 50, 50]);
    p.doc.setFont("helvetica", "normal");
    p.doc.text("•", MARGIN_MM, p.y);
    for (const ln of lines) {
      p.doc.text(ln, 18, p.y);
      p.y += SP.LINE_GAP;
    }
    p.y += 1.5;
  }
  return p;
}

export function wrapText(text: string, fs: number, maxWmm: number): string[] {
  const maxPt = (maxWmm * 72) / 25.4;
  const words = text.split(" ");
  const lines: string[] = [];
  let cur = "";
  for (const w of words) {
    const test = cur ? cur + " " + w : w;
    if (textWidth(test, fs) > maxPt && cur) {
      lines.push(cur);
      cur = w;
    } else {
      cur = test;
    }
  }
  if (cur) lines.push(cur);
  return lines;
}

/** Finish a report: serialize bytes + filename. */
export function finishReport(p: ReportCtx, name: string): BuiltPdf {
  return { bytes: p.doc.toBytes(), filename: reportFilename(name) };
}

/** Trigger a browser download of PDF bytes. */
export function downloadPdf(bytes: Uint8Array, filename: string): void {
  const blob = new Blob([bytes as unknown as BlobPart], { type: "application/pdf" });
  const url = URL.createObjectURL(blob);
  const a = document.createElement("a");
  a.href = url;
  a.download = filename;
  a.style.cssText = "position:fixed;left:-9999px";
  document.body.appendChild(a);
  a.click();
  setTimeout(() => {
    document.body.removeChild(a);
    URL.revokeObjectURL(url);
  }, 200);
}

/** Uint8Array → base64 in chunks (avoids call-stack overflow on large PDFs). */
export function pdfToBase64(bytes: Uint8Array): string {
  const chunks: string[] = [];
  const chunkSize = 8192;
  for (let i = 0; i < bytes.length; i += chunkSize) {
    const slice = bytes.subarray(i, Math.min(i + chunkSize, bytes.length));
    let binary = "";
    for (let j = 0; j < slice.length; j++) binary += String.fromCharCode(slice[j]);
    chunks.push(binary);
  }
  return btoa(chunks.join(""));
}

export { PAGE_W_MM, MARGIN_MM, CONTENT_W_MM };
