/** Guide registry — transcribed verbatim from the legacy guides page (guideCards).
 *  Copy (titles, subtitles, intros) is kept exactly as authored; do not rewrite.
 */
import type { GuideMeta, GuideAudience, AudienceMeta } from "./types";

export const AUDIENCES: AudienceMeta[] = [
  { audience: "Buyer", label: "Buyers", color: "#0F4C75", bg: "#E8F2FB", emoji: "🏠" },
  { audience: "Seller", label: "Sellers", color: "#1A4731", bg: "#E6F4ED", emoji: "🏡" },
  { audience: "Renter", label: "Renters", color: "#3D1A6E", bg: "#EEE8F8", emoji: "🔑" },
  { audience: "Landlord", label: "Landlords", color: "#6B2400", bg: "#FDE8DE", emoji: "🏢" },
];

export const GUIDES: GuideMeta[] = [
  {
    id: "first-time-buyer-checklist",
    audience: "Buyer" as GuideAudience,
    tag: "For Buyers",
    title: "First-Time Buyer's Complete Checklist 2026",
    subtitle: "A step-by-step action plan for buying your first home in Canada",
    intro: "Buying your first home is exciting — and overwhelming. This checklist breaks the entire process into clear phases so nothing falls through the cracks, from saving your down payment to getting the keys on closing day.",
    emoji: "🏠",
    color: "#0F4C75",
    seoTitle: "First-Time Buyer's Complete Checklist 2026 | GetSetSold.ca",
    seoDescription: "A step-by-step action plan for buying your first home in Canada. Free Canadian real estate guide — read online or download the PDF.",
  },
  {
    id: "mortgage-preapproval-explained",
    audience: "Buyer" as GuideAudience,
    tag: "For Buyers",
    title: "Mortgage Pre-Approval Explained for Canadian Buyers",
    subtitle: "What it is, what it isn't, and how to get the strongest possible pre-approval",
    intro: "Pre-approval is the single most important step before house hunting — yet most buyers don't fully understand what it means. This guide explains exactly how it works, what lenders verify, and what can still go wrong after you have one.",
    emoji: "📋",
    color: "#0F4C75",
    seoTitle: "Mortgage Pre-Approval Explained for Canadian Buyers | GetSetSold.ca",
    seoDescription: "What it is, what it isn't, and how to get the strongest possible pre-approval. Free Canadian real estate guide — read online or download the PDF.",
  },
  {
    id: "cmhc-insurance-guide",
    audience: "Buyer" as GuideAudience,
    tag: "For Buyers",
    title: "CMHC Mortgage Insurance: Everything Canadian Buyers Need to Know",
    subtitle: "What it costs, when it's mandatory, and exactly how to avoid it",
    intro: "CMHC mortgage default insurance is mandatory if your down payment is less than 20% — and most first-time buyers pay it. But many buyers don't understand exactly what it costs or how it's calculated. This guide breaks it all down in plain numbers.",
    emoji: "🛡️",
    color: "#0F4C75",
    seoTitle: "CMHC Mortgage Insurance: Everything Canadian Buyers Need to Know | GetSetSold.ca",
    seoDescription: "What it costs, when it's mandatory, and exactly how to avoid it. Free Canadian real estate guide — read online or download the PDF.",
  },
  {
    id: "closing-costs-guide",
    audience: "Buyer" as GuideAudience,
    tag: "For Buyers",
    title: "Canadian Home Buyer Closing Costs: The Complete Guide",
    subtitle: "Every cost you'll pay on closing day — and how to budget for all of them",
    intro: "The down payment is the big number — but closing costs are the shock that catches buyers off guard. Budget 1.5%–4% of the purchase price on top of your down payment. Here is every line item explained.",
    emoji: "💰",
    color: "#0F4C75",
    seoTitle: "Canadian Home Buyer Closing Costs: The Complete Guide | GetSetSold.ca",
    seoDescription: "Every cost you'll pay on closing day — and how to budget for all of them. Free Canadian real estate guide — read online or download the PDF.",
  },
  {
    id: "condo-vs-freehold",
    audience: "Buyer" as GuideAudience,
    tag: "For Buyers",
    title: "Condo vs Freehold: A Complete Comparison for Canadian Buyers",
    subtitle: "What you're actually buying — and which is right for your situation",
    intro: "Condo vs freehold is one of the most consequential decisions Canadian buyers face, especially in cities where condos dominate the entry-level market. Here is an honest breakdown of what you actually own, what it costs, and how to decide.",
    emoji: "🏗️",
    color: "#0F4C75",
    seoTitle: "Condo vs Freehold: A Complete Comparison for Canadian Buyers | GetSetSold.ca",
    seoDescription: "What you're actually buying — and which is right for your situation. Free Canadian real estate guide — read online or download the PDF.",
  },
  {
    id: "bidding-war-strategy",
    audience: "Buyer" as GuideAudience,
    tag: "For Buyers",
    title: "How to Win a Bidding War in Canada Without Overpaying",
    subtitle: "Proven strategies for competing effectively — and knowing when to walk away",
    intro: "Even in a more balanced 2026 market, well-priced homes in desirable areas still attract multiple offers. Here's how to compete strategically without making a financial decision you'll regret.",
    emoji: "⚔️",
    color: "#0F4C75",
    seoTitle: "How to Win a Bidding War in Canada Without Overpaying | GetSetSold.ca",
    seoDescription: "Proven strategies for competing effectively — and knowing when to walk away. Free Canadian real estate guide — read online or download the PDF.",
  },
  {
    id: "home-inspection-guide",
    audience: "Buyer" as GuideAudience,
    tag: "For Buyers",
    title: "Home Inspection Guide for Canadian Buyers",
    subtitle: "What inspectors check, how to read the report, and when to walk away",
    intro: "A home inspection costs $400–$600 and regularly saves buyers tens of thousands of dollars. Here's how to get the most out of one — and how to use the report strategically.",
    emoji: "🔍",
    color: "#0F4C75",
    seoTitle: "Home Inspection Guide for Canadian Buyers | GetSetSold.ca",
    seoDescription: "What inspectors check, how to read the report, and when to walk away. Free Canadian real estate guide — read online or download the PDF.",
  },
  {
    id: "fhsa-guide",
    audience: "Buyer" as GuideAudience,
    tag: "For Buyers",
    title: "First Home Savings Account (FHSA): The Complete Canadian Guide",
    subtitle: "Canada's best new tax benefit for first-time buyers — fully explained",
    intro: "The FHSA launched in 2023 and is unambiguously the best tax tool available to Canadian first-time homebuyers. Contributions are deductible like an RRSP, withdrawals are tax-free like a TFSA, and there is no repayment required. Here's how to maximize it.",
    emoji: "💼",
    color: "#0F4C75",
    seoTitle: "First Home Savings Account (FHSA): The Complete Canadian Guide | GetSetSold.ca",
    seoDescription: "Canada's best new tax benefit for first-time buyers — fully explained. Free Canadian real estate guide — read online or download the PDF.",
  },
  {
    id: "interest-rate-impact",
    audience: "Buyer" as GuideAudience,
    tag: "For Buyers",
    title: "How Interest Rates Affect Your Home Buying Power in Canada",
    subtitle: "What rate changes mean for your mortgage and how to plan around them",
    intro: "Interest rates are the single biggest variable in Canadian housing affordability. A 1% change in your mortgage rate moves your buying power by roughly 8–10%. Here is how to think about rates when planning your purchase.",
    emoji: "📈",
    color: "#0F4C75",
    seoTitle: "How Interest Rates Affect Your Home Buying Power in Canada | GetSetSold.ca",
    seoDescription: "What rate changes mean for your mortgage and how to plan around them. Free Canadian real estate guide — read online or download the PDF.",
  },
  {
    id: "property-tax-guide",
    audience: "Buyer" as GuideAudience,
    tag: "For Buyers",
    title: "Property Tax Guide for Canadian Homeowners",
    subtitle: "How property tax is calculated, what new owners pay, and how to appeal",
    intro: "Property tax is a significant and recurring cost that catches many new homeowners off guard — both the amount and the mechanics. Here's what you need to understand before you buy.",
    emoji: "📊",
    color: "#0F4C75",
    seoTitle: "Property Tax Guide for Canadian Homeowners | GetSetSold.ca",
    seoDescription: "How property tax is calculated, what new owners pay, and how to appeal. Free Canadian real estate guide — read online or download the PDF.",
  },
  {
    id: "new-build-vs-resale",
    audience: "Buyer" as GuideAudience,
    tag: "For Buyers",
    title: "New Build vs Resale Home in Canada: An Honest Comparison",
    subtitle: "Costs, risks, warranties, and timelines compared side by side",
    intro: "New builds and resale homes are fundamentally different purchases — in process, risk, cost, and timeline. Here is an honest comparison to help you decide which is right for your situation.",
    emoji: "🏗️",
    color: "#0F4C75",
    seoTitle: "New Build vs Resale Home in Canada: An Honest Comparison | GetSetSold.ca",
    seoDescription: "Costs, risks, warranties, and timelines compared side by side. Free Canadian real estate guide — read online or download the PDF.",
  },
  {
    id: "bidding-offer-strategy",
    audience: "Buyer" as GuideAudience,
    tag: "For Buyers",
    title: "Writing a Winning Real Estate Offer in Canada",
    subtitle: "What goes into an offer, how conditions work, and negotiation tactics",
    intro: "The Agreement of Purchase and Sale is a legally binding contract the moment both parties sign. Understanding every component before you submit an offer protects you and makes your offer stronger.",
    emoji: "📝",
    color: "#0F4C75",
    seoTitle: "Writing a Winning Real Estate Offer in Canada | GetSetSold.ca",
    seoDescription: "What goes into an offer, how conditions work, and negotiation tactics. Free Canadian real estate guide — read online or download the PDF.",
  },
  {
    id: "land-transfer-tax",
    audience: "Buyer" as GuideAudience,
    tag: "For Buyers",
    title: "Land Transfer Tax in Canada: Province-by-Province Guide 2026",
    subtitle: "What you'll pay in every province — and first-time buyer rebates available",
    intro: "Land transfer tax is one of the largest single closing costs for Canadian buyers — and it varies dramatically by province. Here is exactly what you'll pay across the country and what rebates can reduce the impact.",
    emoji: "🗺️",
    color: "#0F4C75",
    seoTitle: "Land Transfer Tax in Canada: Province-by-Province Guide 2026 | GetSetSold.ca",
    seoDescription: "What you'll pay in every province — and first-time buyer rebates available. Free Canadian real estate guide — read online or download the PDF.",
  },
  {
    id: "home-staging-budget",
    audience: "Seller" as GuideAudience,
    tag: "For Sellers",
    title: "Home Staging on Any Budget: High-ROI Moves for Canadian Sellers",
    subtitle: "What actually moves buyers — most of it costs almost nothing",
    intro: "Professional staging can cost $2,000–$8,000. But the highest-ROI staging moves cost almost nothing. Here's what actually influences buyers emotionally — and how to do most of it yourself.",
    emoji: "🛋️",
    color: "#1A4731",
    seoTitle: "Home Staging on Any Budget: High-ROI Moves for Canadian Sellers | GetSetSold.ca",
    seoDescription: "What actually moves buyers — most of it costs almost nothing. Free Canadian real estate guide — read online or download the PDF.",
  },
  {
    id: "when-to-list",
    audience: "Seller" as GuideAudience,
    tag: "For Sellers",
    title: "When Is the Best Time to List Your Home in Canada?",
    subtitle: "Seasonal market patterns, 2026 conditions, and how timing actually affects your sale",
    intro: "Timing your listing can affect days on market and sale price. Here's what Canadian real estate data shows about seasonal patterns — and when the conventional advice doesn't apply.",
    emoji: "📅",
    color: "#1A4731",
    seoTitle: "When Is the Best Time to List Your Home in Canada? | GetSetSold.ca",
    seoDescription: "Seasonal market patterns, 2026 conditions, and how timing actually affects your sale. Free Canadian real estate guide — read online or download the PDF.",
  },
  {
    id: "commission-negotiation",
    audience: "Seller" as GuideAudience,
    tag: "For Sellers",
    title: "How to Negotiate Real Estate Commission in Canada",
    subtitle: "What's standard, what's negotiable, and what you're actually paying for",
    intro: "Real estate commission is often the largest single cost of selling a home in Canada — and most sellers don't realize it's negotiable. Here's how to have the conversation and what to watch for.",
    emoji: "🤝",
    color: "#1A4731",
    seoTitle: "How to Negotiate Real Estate Commission in Canada | GetSetSold.ca",
    seoDescription: "What's standard, what's negotiable, and what you're actually paying for. Free Canadian real estate guide — read online or download the PDF.",
  },
  {
    id: "capital-gains-guide",
    audience: "Seller" as GuideAudience,
    tag: "For Sellers",
    title: "Capital Gains on Real Estate in Canada: A Seller's Tax Guide",
    subtitle: "Principal residence exemption, rental properties, and what you owe the CRA",
    intro: "Not all Canadian home sales are tax-free. The principal residence exemption is powerful — but it has limits. Rental property sales are taxed differently. Here's what every seller needs to understand before they close.",
    emoji: "💹",
    color: "#1A4731",
    seoTitle: "Capital Gains on Real Estate in Canada: A Seller's Tax Guide | GetSetSold.ca",
    seoDescription: "Principal residence exemption, rental properties, and what you owe the CRA. Free Canadian real estate guide — read online or download the PDF.",
  },
  {
    id: "selling-in-winter",
    audience: "Seller" as GuideAudience,
    tag: "For Sellers",
    title: "Selling Your Home in Winter: A Strategic Guide for Canadians",
    subtitle: "The real advantages of listing in winter — and how to prepare your home for it",
    intro: "Most Canadians instinctively wait for spring to sell. Winter listings are often a smarter strategic play — less competition, more motivated buyers, and a well-prepared home still sells quickly. Here's how to make winter work for you.",
    emoji: "❄️",
    color: "#1A4731",
    seoTitle: "Selling Your Home in Winter: A Strategic Guide for Canadians | GetSetSold.ca",
    seoDescription: "The real advantages of listing in winter — and how to prepare your home for it. Free Canadian real estate guide — read online or download the PDF.",
  },
  {
    id: "upgrading-vs-downsizing",
    audience: "Seller" as GuideAudience,
    tag: "For Sellers",
    title: "Upgrading vs Downsizing: The Financial Guide for Canadian Sellers",
    subtitle: "How to make the numbers work whether you're going bigger or smaller",
    intro: "Selling and buying at the same time is one of the most financially complex real estate moves Canadians make. Whether upsizing or downsizing, getting the sequence and timing right determines whether the experience is smooth or stressful.",
    emoji: "🔄",
    color: "#1A4731",
    seoTitle: "Upgrading vs Downsizing: The Financial Guide for Canadian Sellers | GetSetSold.ca",
    seoDescription: "How to make the numbers work whether you're going bigger or smaller. Free Canadian real estate guide — read online or download the PDF.",
  },
  {
    id: "prelisting-inspection",
    audience: "Seller" as GuideAudience,
    tag: "For Sellers",
    title: "Pre-Listing Home Inspection: Should Canadian Sellers Do One?",
    subtitle: "The case for inspecting your own home before buyers do — and what to do with the results",
    intro: "Most sellers don't inspect their own home before listing. A pre-listing inspection changes the entire dynamic of your sale and shifts control back to you. Here's when it makes sense and exactly what to do with the results.",
    emoji: "🔎",
    color: "#1A4731",
    seoTitle: "Pre-Listing Home Inspection: Should Canadian Sellers Do One? | GetSetSold.ca",
    seoDescription: "The case for inspecting your own home before buyers do — and what to do with the results. Free Canadian real estate guide — read online or download the PDF.",
  },
  {
    id: "moving-timeline",
    audience: "Seller" as GuideAudience,
    tag: "For Sellers",
    title: "Selling and Moving Timeline for Canadian Sellers",
    subtitle: "A week-by-week countdown from listing preparation to keys handed over",
    intro: "Selling and moving involves dozens of parallel tasks across 8–12 weeks. This timeline works backward from your closing date so nothing is left to the last minute.",
    emoji: "📦",
    color: "#1A4731",
    seoTitle: "Selling and Moving Timeline for Canadian Sellers | GetSetSold.ca",
    seoDescription: "A week-by-week countdown from listing preparation to keys handed over. Free Canadian real estate guide — read online or download the PDF.",
  },
  {
    id: "market-outlook-2026",
    audience: "Seller" as GuideAudience,
    tag: "For Sellers",
    title: "Canadian Real Estate Market Outlook for Sellers in 2026",
    subtitle: "What the current market means for pricing, timing, and expectations",
    intro: "The Canadian market in 2026 looks meaningfully different from the volatility of 2020–2023. Sellers who understand the macro environment make better pricing and timing decisions. Here is what the data shows.",
    emoji: "🌐",
    color: "#1A4731",
    seoTitle: "Canadian Real Estate Market Outlook for Sellers in 2026 | GetSetSold.ca",
    seoDescription: "What the current market means for pricing, timing, and expectations. Free Canadian real estate guide — read online or download the PDF.",
  },
  {
    id: "finding-rental-canada",
    audience: "Renter" as GuideAudience,
    tag: "For Renters",
    title: "How to Find a Rental in Canada's Competitive Market",
    subtitle: "Where to search, how to stand out as an applicant, and scams to avoid",
    intro: "Canada's rental market remains highly competitive in major cities. Here's how to search smarter, stand out as an applicant, and protect yourself from the scams that cost renters time and money every year.",
    emoji: "🔑",
    color: "#3D1A6E",
    seoTitle: "How to Find a Rental in Canada's Competitive Market | GetSetSold.ca",
    seoDescription: "Where to search, how to stand out as an applicant, and scams to avoid. Free Canadian real estate guide — read online or download the PDF.",
  },
  {
    id: "tenant-insurance",
    audience: "Renter" as GuideAudience,
    tag: "For Renters",
    title: "Tenant Insurance Guide for Canadian Renters",
    subtitle: "What it covers, what it costs, and why no renter should be without it",
    intro: "Tenant insurance is one of the most affordable and valuable financial products a renter can have — yet most tenants don't carry it. Here's what it actually covers, what it costs, and exactly why you need it.",
    emoji: "🛡️",
    color: "#3D1A6E",
    seoTitle: "Tenant Insurance Guide for Canadian Renters | GetSetSold.ca",
    seoDescription: "What it covers, what it costs, and why no renter should be without it. Free Canadian real estate guide — read online or download the PDF.",
  },
  {
    id: "subletting-rights",
    audience: "Renter" as GuideAudience,
    tag: "For Renters",
    title: "Subletting Your Rental Unit in Canada: What's Actually Legal",
    subtitle: "Your legal right to sublet and how to do it properly in every province",
    intro: "Many tenants don't realize they have a legal right to sublet in most Canadian provinces — landlords cannot simply refuse without a valid reason. Here's what the law actually says and how to sublet correctly.",
    emoji: "🔄",
    color: "#3D1A6E",
    seoTitle: "Subletting Your Rental Unit in Canada: What's Actually Legal | GetSetSold.ca",
    seoDescription: "Your legal right to sublet and how to do it properly in every province. Free Canadian real estate guide — read online or download the PDF.",
  },
  {
    id: "breaking-lease",
    audience: "Renter" as GuideAudience,
    tag: "For Renters",
    title: "How to Break a Lease Early in Canada",
    subtitle: "Your legal options, your financial exposure, and the right way to leave",
    intro: "Life doesn't always align with a lease. Job relocation, relationship changes, or a better housing opportunity can require breaking a fixed-term lease before it ends. Here are your legal options and how to minimize the cost.",
    emoji: "🚪",
    color: "#3D1A6E",
    seoTitle: "How to Break a Lease Early in Canada | GetSetSold.ca",
    seoDescription: "Your legal options, your financial exposure, and the right way to leave. Free Canadian real estate guide — read online or download the PDF.",
  },
  {
    id: "disputing-rent-increase",
    audience: "Renter" as GuideAudience,
    tag: "For Renters",
    title: "How to Dispute a Rent Increase in Canada",
    subtitle: "When increases are legal, when they're not, and exactly what to do about it",
    intro: "Many Canadian tenants accept rent increases without question — including illegal ones. Here's how to verify whether your increase is valid, and what to do if it isn't.",
    emoji: "📋",
    color: "#3D1A6E",
    seoTitle: "How to Dispute a Rent Increase in Canada | GetSetSold.ca",
    seoDescription: "When increases are legal, when they're not, and exactly what to do about it. Free Canadian real estate guide — read online or download the PDF.",
  },
  {
    id: "roommate-agreement",
    audience: "Renter" as GuideAudience,
    tag: "For Renters",
    title: "Roommate Agreement Guide for Canadian Renters",
    subtitle: "What to agree on in writing before you move in together — and avoid disputes later",
    intro: "The majority of roommate conflicts come from expectations that were never defined. A written roommate agreement — even between close friends — prevents the conversations that damage relationships. Here's exactly what to cover.",
    emoji: "👥",
    color: "#3D1A6E",
    seoTitle: "Roommate Agreement Guide for Canadian Renters | GetSetSold.ca",
    seoDescription: "What to agree on in writing before you move in together — and avoid disputes later. Free Canadian real estate guide — read online or download the PDF.",
  },
  {
    id: "moving-out-checklist",
    audience: "Renter" as GuideAudience,
    tag: "For Renters",
    title: "Moving Out Checklist for Canadian Renters",
    subtitle: "How to leave your rental properly and protect your deposit",
    intro: "Move-out is where most tenant-landlord disputes arise. A systematic approach to leaving the unit in excellent documented condition is your best protection for recovering your full deposit.",
    emoji: "📦",
    color: "#3D1A6E",
    seoTitle: "Moving Out Checklist for Canadian Renters | GetSetSold.ca",
    seoDescription: "How to leave your rental properly and protect your deposit. Free Canadian real estate guide — read online or download the PDF.",
  },
  {
    id: "rent-affordability",
    audience: "Renter" as GuideAudience,
    tag: "For Renters",
    title: "How Much Should You Spend on Rent in Canada?",
    subtitle: "The 30% rule, reality in major cities, and practical strategies to manage housing costs",
    intro: "The classic guideline says rent should be no more than 30% of gross income. In Toronto and Vancouver, this is unworkable for most renters. Here's how to think about housing costs practically — and what you can actually do about high rents.",
    emoji: "💸",
    color: "#3D1A6E",
    seoTitle: "How Much Should You Spend on Rent in Canada? | GetSetSold.ca",
    seoDescription: "The 30% rule, reality in major cities, and practical strategies to manage housing costs. Free Canadian real estate guide — read online or download the PDF.",
  },
  {
    id: "landlord-tax-deductions",
    audience: "Landlord" as GuideAudience,
    tag: "For Landlords",
    title: "Tax Deductions for Canadian Landlords: The Complete Guide",
    subtitle: "Every legitimate expense deductible against rental income — organized by category",
    intro: "Rental income is taxable in Canada — but so many legitimate expenses are deductible that your actual tax burden can be quite low if you are organized. Here is every deduction the CRA allows, with practical guidance on claiming them.",
    emoji: "🧾",
    color: "#6B2400",
    seoTitle: "Tax Deductions for Canadian Landlords: The Complete Guide | GetSetSold.ca",
    seoDescription: "Every legitimate expense deductible against rental income — organized by category. Free Canadian real estate guide — read online or download the PDF.",
  },
  {
    id: "above-guideline-rent",
    audience: "Landlord" as GuideAudience,
    tag: "For Landlords",
    title: "Above-Guideline Rent Increases in Ontario: A Landlord's Guide",
    subtitle: "When you can apply, how the LTB process works, and what to expect",
    intro: "Ontario's rent guideline caps most annual increases at 2.5% in 2026. When a landlord's actual costs exceed this — due to major capital work or extraordinary operating cost increases — an above-guideline increase application is possible. Here's how.",
    emoji: "📈",
    color: "#6B2400",
    seoTitle: "Above-Guideline Rent Increases in Ontario: A Landlord's Guide | GetSetSold.ca",
    seoDescription: "When you can apply, how the LTB process works, and what to expect. Free Canadian real estate guide — read online or download the PDF.",
  },
  {
    id: "condo-rental-rules",
    audience: "Landlord" as GuideAudience,
    tag: "For Landlords",
    title: "Renting Out a Condo in Canada: Rules Every Landlord Must Know",
    subtitle: "Condo corporation rules, short-term rental restrictions, and your compliance obligations",
    intro: "Condo landlords operate under two layers of authority simultaneously: provincial landlord-tenant law and the condo corporation's declaration, bylaws, and rules. Both apply. Violating either has real consequences. Here's what you need to know.",
    emoji: "🏙️",
    color: "#6B2400",
    seoTitle: "Renting Out a Condo in Canada: Rules Every Landlord Must Know | GetSetSold.ca",
    seoDescription: "Condo corporation rules, short-term rental restrictions, and your compliance obligations. Free Canadian real estate guide — read online or download the PDF.",
  },
  {
    id: "landlord-insurance",
    audience: "Landlord" as GuideAudience,
    tag: "For Landlords",
    title: "Insurance for Canadian Landlords: What You Actually Need",
    subtitle: "Why home insurance doesn't cover rentals — and what policy you actually need",
    intro: "The most common and expensive insurance mistake landlords make is assuming their existing homeowner or condo insurance covers a rental property. It doesn't. Here's what coverage you need and what to look for in a landlord policy.",
    emoji: "🛡️",
    color: "#6B2400",
    seoTitle: "Insurance for Canadian Landlords: What You Actually Need | GetSetSold.ca",
    seoDescription: "Why home insurance doesn't cover rentals — and what policy you actually need. Free Canadian real estate guide — read online or download the PDF.",
  },
  {
    id: "lease-renewal",
    audience: "Landlord" as GuideAudience,
    tag: "For Landlords",
    title: "Lease Renewal Guide for Canadian Landlords",
    subtitle: "What legally happens when a lease expires and how to handle renewal strategically",
    intro: "The end of a fixed-term lease is one of the most misunderstood moments in a Canadian tenancy. Most landlords don't know what the law actually requires — and many tenants don't either. Here's exactly what happens.",
    emoji: "🔄",
    color: "#6B2400",
    seoTitle: "Lease Renewal Guide for Canadian Landlords | GetSetSold.ca",
    seoDescription: "What legally happens when a lease expires and how to handle renewal strategically. Free Canadian real estate guide — read online or download the PDF.",
  },
  {
    id: "property-management-diy",
    audience: "Landlord" as GuideAudience,
    tag: "For Landlords",
    title: "DIY Property Management for Small Canadian Landlords",
    subtitle: "How to manage your rental professionally with the right systems — not just time",
    intro: "Property managers charge 8–12% of monthly rent — around $2,400–$3,600 per year on a $2,500/month unit. Managing your rental well yourself is entirely possible with the right systems. Here's how.",
    emoji: "🔧",
    color: "#6B2400",
    seoTitle: "DIY Property Management for Small Canadian Landlords | GetSetSold.ca",
    seoDescription: "How to manage your rental professionally with the right systems — not just time. Free Canadian real estate guide — read online or download the PDF.",
  },
  {
    id: "tenant-screening",
    audience: "Landlord" as GuideAudience,
    tag: "For Landlords",
    title: "Advanced Tenant Screening for Canadian Landlords",
    subtitle: "A systematic process to find reliable tenants and avoid costly mistakes",
    intro: "The most experienced landlords have a consistent, systematic tenant screening process — not to be difficult, but because one bad tenancy is extraordinarily expensive. Here's how to screen effectively and legally.",
    emoji: "🔍",
    color: "#6B2400",
    seoTitle: "Advanced Tenant Screening for Canadian Landlords | GetSetSold.ca",
    seoDescription: "A systematic process to find reliable tenants and avoid costly mistakes. Free Canadian real estate guide — read online or download the PDF.",
  },
  {
    id: "eviction-notices",
    audience: "Landlord" as GuideAudience,
    tag: "For Landlords",
    title: "Ontario Eviction Notices: A Complete Landlord Guide",
    subtitle: "Every notice form, exactly when to use it, and how to serve it correctly",
    intro: "Eviction in Ontario is a precise legal process where the wrong form, an incorrect amount, or improper service results in dismissal at the LTB — and starting over. Here is every notice a landlord needs, explained correctly.",
    emoji: "📝",
    color: "#6B2400",
    seoTitle: "Ontario Eviction Notices: A Complete Landlord Guide | GetSetSold.ca",
    seoDescription: "Every notice form, exactly when to use it, and how to serve it correctly. Free Canadian real estate guide — read online or download the PDF.",
  },
  {
    id: "real-estate-glossary",
    audience: "Buyer" as GuideAudience,
    tag: "General Reference",
    title: "Canadian Real Estate Glossary: Every Term Explained",
    subtitle: "A complete A–Z reference for buyers, sellers, renters, and landlords",
    intro: "Real estate transactions use a language of their own — and agents, lawyers, and lenders use these terms casually, assuming everyone knows them. This glossary covers every term you'll encounter in Canadian real estate.",
    emoji: "📖",
    color: "#0F4C75",
    seoTitle: "Canadian Real Estate Glossary: Every Term Explained | GetSetSold.ca",
    seoDescription: "A complete A–Z reference for buyers, sellers, renters, and landlords. Free Canadian real estate guide — read online or download the PDF.",
  },
  {
    id: "fhsa-rrsp-combo",
    audience: "Buyer" as GuideAudience,
    tag: "For Buyers",
    title: "FHSA + RRSP Home Buyers' Plan: Combining Both Programs",
    subtitle: "How to stack both programs for up to $75,000 tax-free toward your first home",
    intro: "Canada offers two major tax-advantaged programs for first-time buyers — and you can use them simultaneously. Here's exactly how to combine the FHSA and RRSP HBP to maximize your tax-free down payment.",
    emoji: "💰",
    color: "#0F4C75",
    seoTitle: "FHSA + RRSP Home Buyers' Plan: Combining Both Programs | GetSetSold.ca",
    seoDescription: "How to stack both programs for up to $75,000 tax-free toward your first home. Free Canadian real estate guide — read online or download the PDF.",
  },
  {
    id: "rent-vs-buy",
    audience: "Buyer" as GuideAudience,
    tag: "General Reference",
    title: "Rent vs Buy in Canada: An Honest 2026 Analysis",
    subtitle: "The real financial comparison — with actual numbers for Canadian markets",
    intro: "The rent vs buy debate in Canada is often oversimplified in both directions. This guide walks through the actual financial comparison with realistic numbers — so you can make the decision that's right for your specific situation.",
    emoji: "⚖️",
    color: "#0F4C75",
    seoTitle: "Rent vs Buy in Canada: An Honest 2026 Analysis | GetSetSold.ca",
    seoDescription: "The real financial comparison — with actual numbers for Canadian markets. Free Canadian real estate guide — read online or download the PDF.",
  },
  {
    id: "power-of-sale-foreclosure",
    audience: "Buyer" as GuideAudience,
    tag: "General Reference",
    title: "Power of Sale and Foreclosure in Canada: What Buyers and Owners Need to Know",
    subtitle: "How distressed property sales work — and your rights as an owner facing default",
    intro: "When a homeowner defaults on their mortgage, Canadian lenders have two main remedies: power of sale and foreclosure. Both have significant implications for the owner and potential opportunities for buyers. Here's how each works.",
    emoji: "⚠️",
    color: "#0F4C75",
    seoTitle: "Power of Sale and Foreclosure in Canada: What Buyers and Owners Need to Know | GetSetSold.ca",
    seoDescription: "How distressed property sales work — and your rights as an owner facing default. Free Canadian real estate guide — read online or download the PDF.",
  },
  {
    id: "estate-real-estate",
    audience: "Seller" as GuideAudience,
    tag: "General Reference",
    title: "Dealing With Real Estate in an Estate in Canada",
    subtitle: "What happens to a property when someone dies — and how to navigate it",
    intro: "Dealing with real estate in a deceased person's estate is a process that combines grief with significant legal and financial complexity. This guide helps executors, beneficiaries, and family members understand what is involved.",
    emoji: "📜",
    color: "#1A4731",
    seoTitle: "Dealing With Real Estate in an Estate in Canada | GetSetSold.ca",
    seoDescription: "What happens to a property when someone dies — and how to navigate it. Free Canadian real estate guide — read online or download the PDF.",
  },
  {
    id: "investment-property-guide",
    audience: "Landlord" as GuideAudience,
    tag: "For Landlords",
    title: "Buying Your First Investment Property in Canada",
    subtitle: "How to evaluate, finance, and manage a rental property for long-term wealth",
    intro: "Real estate has built more generational wealth in Canada than almost any other asset class. But investment property is not passive income — it's an active business that requires planning, capital, and ongoing management. Here's how to approach it correctly.",
    emoji: "📊",
    color: "#6B2400",
    seoTitle: "Buying Your First Investment Property in Canada | GetSetSold.ca",
    seoDescription: "How to evaluate, finance, and manage a rental property for long-term wealth. Free Canadian real estate guide — read online or download the PDF.",
  },
];

export const GUIDE_COUNT = GUIDES.length;

export function getGuide(id: string): GuideMeta | null {
  return GUIDES.find((g) => g.id === id) ?? null;
}

export function getGuidesByAudience(aud: GuideAudience | "All"): GuideMeta[] {
  if (aud === "All") return GUIDES;
  return GUIDES.filter((g) => g.audience === aud);
}

export function getAudienceMeta(aud: GuideAudience): AudienceMeta {
  const meta = AUDIENCES.find((a) => a.audience === aud);
  if (!meta) throw new Error(`Unknown audience: ${aud}`);
  return meta;
}

/** Legacy ?c= / #hash id compatibility — ids are already canonical slugs. */
export const LEGACY_IDS: Record<string, string> = {
  "first-time-buyer-checklist": "first-time-buyer-checklist",
  "mortgage-preapproval-explained": "mortgage-preapproval-explained",
  "cmhc-insurance-guide": "cmhc-insurance-guide",
  "closing-costs-guide": "closing-costs-guide",
  "condo-vs-freehold": "condo-vs-freehold",
  "bidding-war-strategy": "bidding-war-strategy",
  "home-inspection-guide": "home-inspection-guide",
  "fhsa-guide": "fhsa-guide",
  "interest-rate-impact": "interest-rate-impact",
  "property-tax-guide": "property-tax-guide",
  "new-build-vs-resale": "new-build-vs-resale",
  "bidding-offer-strategy": "bidding-offer-strategy",
  "land-transfer-tax": "land-transfer-tax",
  "home-staging-budget": "home-staging-budget",
  "when-to-list": "when-to-list",
  "commission-negotiation": "commission-negotiation",
  "capital-gains-guide": "capital-gains-guide",
  "selling-in-winter": "selling-in-winter",
  "upgrading-vs-downsizing": "upgrading-vs-downsizing",
  "prelisting-inspection": "prelisting-inspection",
  "moving-timeline": "moving-timeline",
  "market-outlook-2026": "market-outlook-2026",
  "finding-rental-canada": "finding-rental-canada",
  "tenant-insurance": "tenant-insurance",
  "subletting-rights": "subletting-rights",
  "breaking-lease": "breaking-lease",
  "disputing-rent-increase": "disputing-rent-increase",
  "roommate-agreement": "roommate-agreement",
  "moving-out-checklist": "moving-out-checklist",
  "rent-affordability": "rent-affordability",
  "landlord-tax-deductions": "landlord-tax-deductions",
  "above-guideline-rent": "above-guideline-rent",
  "condo-rental-rules": "condo-rental-rules",
  "landlord-insurance": "landlord-insurance",
  "lease-renewal": "lease-renewal",
  "property-management-diy": "property-management-diy",
  "tenant-screening": "tenant-screening",
  "eviction-notices": "eviction-notices",
  "real-estate-glossary": "real-estate-glossary",
  "fhsa-rrsp-combo": "fhsa-rrsp-combo",
  "rent-vs-buy": "rent-vs-buy",
  "power-of-sale-foreclosure": "power-of-sale-foreclosure",
  "estate-real-estate": "estate-real-estate",
  "investment-property-guide": "investment-property-guide",
};
