import Link from "next/link";
import { getHpiMarket, hpiMarketForCity, fmtMoney, fmtPct, pctTone } from "@/lib/hpi";
import { HpiChart } from "./HpiChart";

/**
 * "Local Market Pulse" — realtor.ca-style market section at the end of
 * neighbourhood pages. Market name + intro, price card, YoY chart,
 * 10-year chart, contact CTA. Hover tooltips on both charts.
 */
export async function LocalMarketPulse({ citySlug, cityName }: { citySlug: string; cityName: string }) {
  const hpiSlug = hpiMarketForCity(citySlug);
  if (!hpiSlug) return null;
  const market = await getHpiMarket(hpiSlug);
  if (!market) return null;

  const yoy = market.latest.yoyChange;
  const yoyTone = pctTone(yoy);

  const yoyPoints = market.history12m.map((h) => ({ month: h.month, value: h.compositeBenchmark, hpi: h.compositeHPI }));
  // Annualize full history for the 10-year chart (Dec value per year, last 10 years)
  const byYear = new Map<string, { month: string; value: number }>();
  for (const h of market.fullHistory) {
    const y = h.month.slice(0, 4);
    byYear.set(y, { month: `${y}-12`, value: h.compositeBenchmark });
  }
  const tenYr = [...byYear.entries()].sort().slice(-10).map(([, v]) => ({ month: v.month, value: v.value }));

  return (
    <section className="mt-12 border-t border-line pt-8" aria-label="Local market pulse">
      <h2 className="text-2xl font-bold tracking-tight">{market.name} Market</h2>
      <p className="mt-3 max-w-3xl text-[15px] leading-relaxed text-muted">
        Use our home price trends to better gauge local market conditions and plan your next move.
        The graphs below show benchmark prices of homes sold in the area. Data generated by MLS®
        Systems and the MLS® Home Price Index (HPI) — Canada&apos;s most advanced tool to gauge
        local home price levels and trends.
      </p>

      <div className="mt-6 grid gap-6 md:grid-cols-3">
        {/* Price card */}
        <div className="flex flex-col items-center justify-center rounded-2xl border-2 border-black bg-white p-8 text-center shadow-sm">
          <span className="text-sm font-semibold">Market Price (CAD)</span>
          <span className="mt-1 text-4xl font-bold tracking-tight">{fmtMoney(market.latest.compositeBenchmark)}</span>
          <span className="mt-5 text-sm font-semibold">Difference over last year (%)</span>
          <span className={`mt-1 text-4xl font-bold ${yoyTone === "neg" ? "text-red-700" : yoyTone === "pos" ? "text-green-700" : ""}`}>
            {fmtPct(yoy)}
          </span>
        </div>

        {/* YoY chart */}
        <div className="rounded-2xl border border-line bg-white p-5">
          <h3 className="mb-2 text-center text-[15px] font-semibold">Year over year</h3>
          <HpiChart points={yoyPoints} height={220} />
        </div>

        {/* 10-year chart */}
        <div className="rounded-2xl border border-line bg-white p-5">
          <h3 className="mb-2 text-center text-[15px] font-semibold">Past 10 years</h3>
          <HpiChart points={tenYr} height={220} />
        </div>
      </div>

      <p className="mt-6 text-[15px]">
        <Link href="/contact" className="font-medium text-[#0066CC] underline">
          Contact us
        </Link>{" "}
        for more detailed market information.
      </p>
      <p className="mt-2 text-xs text-muted">
        Source: CREA MLS® Home Price Index · {market.name} · Updated {market.lastUpdated}
      </p>
    </section>
  );
}
