-- Feature section: header + feature rows in ONE section block, 4 layouts (simple, lines, cross, bands),
-- with an optional single color for the whole section. Existing blocks are untouched.

insert into public.block_types (key, name, category, default_data) values
('feature_section', 'Feature section (header + rows)', 'content', '{"layout": "simple", "eyebrow": "[Audience or category]", "heading": "[A short, confident headline.]", "text": "[One or two sentences that frame the section.]", "items": [{"title": "[First feature]", "text": "[One or two lines on what this gives the visitor.]"}, {"title": "[Second feature]", "text": "[One or two lines on what this gives the visitor.]"}, {"title": "[Third feature]", "text": "[One or two lines on what this gives the visitor.]"}], "link": {"label": "[Explore the plan]", "href": "/"}}')
on conflict (key) do nothing;

insert into public.section_presets (name, category, description, sort_order, blocks) values
('Feature section: simple card', 'Feature', 'One clean card: header on the left, feature rows on the right.', 20, '[{"type": "feature_section", "data": {"layout": "simple", "eyebrow": "[Audience or category]", "heading": "[A short, confident headline.]", "text": "[One or two sentences that frame the section.]", "items": [{"title": "[First feature]", "text": "[One or two lines on what this gives the visitor.]"}, {"title": "[Second feature]", "text": "[One or two lines on what this gives the visitor.]"}, {"title": "[Third feature]", "text": "[One or two lines on what this gives the visitor.]"}], "link": {"label": "[Explore the plan]", "href": "/"}}}]'),
('Feature section: fine lines', 'Feature', 'Header left, divided rows right, each with its own link.', 21, '[{"type": "feature_section", "data": {"layout": "lines", "eyebrow": "[Audience or category]", "heading": "[A short, confident headline.]", "text": "", "items": [{"title": "[First feature]", "text": "[One or two lines on what this gives the visitor.]", "href": "/", "link_label": "[Learn more]"}, {"title": "[Second feature]", "text": "[One or two lines on what this gives the visitor.]", "href": "/", "link_label": "[Learn more]"}, {"title": "[Third feature]", "text": "[One or two lines on what this gives the visitor.]", "href": "/", "link_label": "[Learn more]"}], "footnote": "[A short reassurance line goes here.]"}}]'),
('Feature section: structural cross', 'Feature', 'Filled color card with a grid of features. Uses your brand color.', 22, '[{"type": "feature_section", "data": {"layout": "cross", "eyebrow": "[Audience or category]", "heading": "[A short, confident headline.]", "text": "", "items": [{"title": "[First feature]", "text": "[One or two lines on what this gives the visitor.]", "href": "/", "link_label": "[Learn more]"}, {"title": "[Second feature]", "text": "[One or two lines on what this gives the visitor.]", "href": "/", "link_label": "[Learn more]"}, {"title": "[Third feature]", "text": "[One or two lines on what this gives the visitor.]", "href": "/", "link_label": "[Learn more]"}], "footnote": "[A short reassurance line goes here.]"}}]'),
('Feature section: indexed bands', 'Feature', 'Dark header panel, light bands on the right, each with a link.', 23, '[{"type": "feature_section", "data": {"layout": "bands", "eyebrow": "[Audience or category]", "heading": "[A short, confident headline.]", "text": "", "items": [{"title": "[First feature]", "text": "[One or two lines on what this gives the visitor.]", "href": "/", "link_label": "[Learn more]"}, {"title": "[Second feature]", "text": "[One or two lines on what this gives the visitor.]", "href": "/", "link_label": "[Learn more]"}, {"title": "[Third feature]", "text": "[One or two lines on what this gives the visitor.]", "href": "/", "link_label": "[Learn more]"}], "footnote": "[A short reassurance line goes here.]"}}]');
